# question 1
# The reason one cannot take crime and police data from different cities and run a regression that will have a generalized model for the entire dataset is because of exogenous factors that may be at play in one city compared to another. For example, if city A has only a population of 100, compared to city B of 100,000, doubling the number of police personnel in each city would have a different effect on crime, if we presume that police is negatively correlated with crime. At the same time, we also do not take into consideration the concept as to whether or not there are special events held in each city that would artifically increase the number of plice personnel that other cities do not enact - such as washington DC's terrorism alert that would deploy more law enforcement.

# question 2
# The researchers utilized the terror alert system that was in place in Washington DC. This alert serves as a dummy variable that would artificially increase the number of police in the street that would be exogenous to the street crime norm. The researchers found that there was a small, but statistically significant effect from deploying more police in the streets from comparing days where there was no alert to days where there was an alert.

# question 3
# However, the consideration here is whether or not another factor - such as tourism, would be indirectly tied to crime levels given that tourists are a prime population at risk to crime. The researchers addressed this issue by examining the relative metro ridership comparing days when the alert was in place and when it was not. If the two days are the same, this instrumental variable effectively stated that despite the alert rating, passengers and by extension tourists, still went on with their day-to-day lives.

# question 4
# The model here is using a clustered regression of the effects of a high alert on specific district in Washington DC - asking what is the effect of a high alert on crime controlling for the fact that different subdivisions (districts) within Washington DC would have pre-set levels of law enforcement that is not consistent throughout the city - namely the Capitol National Mall compared to other districts. The conclusion that the researchers came to was that yes, a high alert increased police presence and decreased crime, but one you control for specific districts, most the decrease was found within one district - the Capitol Mall.