# Conclusion

# Bibliography

Anderson, Michael L. 2008. *"Multiple Inference and Gender Differences in the Effects of Early Intervention: A Reevaluation of the Abecedarian, Perry Preschool, and Early Training Projects."* Journal of the American Statistical Association, 103(484): 1481-95

Barnett, W. Steven. 1992. *"Benefits of Compensatory Preschool Education."* Journal of Human Resources, 27(2): 279-312

Barnett, W. Steven, Jason T. Hustedt, Allison H. Friedman, Judi Stevenson Boyd, and Pat Ainsworth. 2007. *The State of Preschool 2007: State Preschool Yearbook.* New Brunswick, NJ: National Institute for Early Education Research.

Belfield, Clive R., Milagros Nores, Steven Barnett, and Lawrence Schweinhart. 2006. *"The High/ Scope Perry Preschool Program: Cost-Benefit Analysis Using Data from the Age-40 Followup."* Journal of Human Resources, 40(1): 162-90.

Campbell, Frances A., Craig T. Ramey, Elizabeth Pungello, Joseph Sparling, and Shari Miller-Johnson. 2002. *"Early Childhood Education: Young Adult Outcomes From the Abecedarian Project."* Applied Developmental Science, 6(1): 42-57.

Case, Anne, Darren Lubotsky, and Christina Paxson. 2002. *"Economic Status and Health in Childhood: The Origins of the Gradient."* American Economic Review, 92(5): 1308-34.

Currie, Janet. 2001. *"Early Childhood Education Programs."* Journal of Economic Perspectives, 15(2): 213-38.

Currie, Janet, and Matthew Neidell. 2007. *"Getting inside the 'Black Box' of Head Start Quality: What Matters and What Doesn't."* Economics of Education Review, 26(1): 83-99.

Currie, Janet, and Duncan Thomas. 1995. *"Does Head Start Make a Difference?"* American Economic Review, 85(3): 341-64

Currie, Janet, and Duncan Thomas. 2000. *"School Quality and the Longer-Term Effects of Head Start."* Journal of Human Resources, 35(4): 755-74.

Garces, Eliana, Duncan Thomas, and Janet Currie. 2002. *"Longer-Term Effects of Head Start."* American Economic Review, 92(4): 999-1012.

Gormley, William T., Jr., and Ted Gayer. 2005. *"Promoting School Readiness in Oklahoma: An Evaluation of Tulsa's Pre-K Program."* Journal of Human Resources, 40(3): 533-58.

Heckman, James J. 2006. *"Skill Formation and the Economics of Investing in Disadvantaged Children."* Science, 312(5782): 1900-1902

Levin, Henry M., Clive Belfield, Peter Muennig, and Cecilia Rouse. 2007. *"The Public Returns to Public Educational Investments in African-American Males."* Economics of Education Review, 26(6): 699-708.

Ludwig, Jens, and Douglas L. Miller. 2007. *"Does Head Start Improve Children's Life Chances? Evidence from a Regression Discontinuity Design."* Quarterly Journal of Economics, 122(1): 159-208.

Ludwig, Jens, and Deborah A. Phillips. 2007. *"The Benefits and Costs of Head Start."* National Bureau of Economic Research Working Paper 12973

Ludwig, Jens, and Deborah A. Phillips. 2008. *"Long-Term Effects of Head Start on Low-Income Children."* Annals of the New York Academy of Sciences, 1136: 257-68.

Neal, Derek A., and William R. Johnson. 1996. *"The Role of Premarket Factors in Black-White Wage Differences."* Journal of Political Economy, 104(5): 869-95.
